# Generated by Django 2.0.10 on 2019-01-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='img/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.AddField(
            model_name='emblema',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autostickrapp.Marca'),
        ),
    ]
