# Generated by Django 2.0.10 on 2019-01-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autostickrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
