# Generated by Django 2.0.10 on 2019-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autostickrapp', '0002_auto_20190116_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblema',
            name='marca',
        ),
        migrations.AddField(
            model_name='emblema',
            name='marca',
            field=models.ManyToManyField(to='autostickrapp.Marca'),
        ),
    ]
