# Generated by Django 2.0.10 on 2019-03-06 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autostickrapp', '0007_auto_20190306_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 13, 16, 19, 94290, tzinfo=utc)),
        ),
    ]
