# Generated by Django 2.0.10 on 2019-03-07 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autostickrapp', '0009_auto_20190306_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 6, 14, 52, 544358, tzinfo=utc)),
        ),
    ]
