# Generated by Django 2.0.10 on 2019-03-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autostickrapp', '0010_auto_20190307_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='key_expires',
        ),
    ]
